# Generated by Django 3.0.3 on 2020-12-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20201230_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='university',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('url', models.TextField(max_length=1000)),
                ('formation', models.ManyToManyField(blank=True, null=True, to='university.Formation')),
            ],
        ),
    ]
