# Generated by Django 3.0.3 on 2021-01-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='formation',
        ),
        migrations.AlterField(
            model_name='university',
            name='image',
            field=models.TextField(),
        ),
    ]
